# Generated by Django 3.0.8 on 2020-09-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20200909_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
